name: 'Setup Frontend Dependencies'
description: 'Install pnpm and install dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: ./frontend/package.json

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: ./frontend
