export enum DocumentTypeCode {
  VERWALTUNGSVORSCHRIFTEN = 'VERWALTUNGSVORSCHRIFTEN',
  LITERATUR_UNSELBSTSTAENDIG = 'LITERATUR_UNSELBSTSTAENDIG',
  LITERATUR_SELBSTSTAENDIG = 'LITERATUR_SELBSTSTAENDIG',
}

export type DocumentType = {
  uuid?: string
  abbreviation: string
  name: string
}
