spring:
  application.name: ris-adm-vwv-backend
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:ris_adm_vwv}?currentSchema=${database.schema:adm_vwv}

management:
  endpoint:
    health:
      probes:
        enabled: true

sentry:
  dsn: ${SENTRY_DSN}
  environment: staging
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  # Set traces_sample_rate to 1.0 to capture 100% of transactions for tracing.
  tracesSampleRate: 0.01
  ignoreTransactions: ["/actuator/**"]

oauth2:
  issuer-uri: https://neuris.login.bare.id/auth/realms/development
