spring:
  application.name: ris-adm-vwv-backend
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:ris_adm_vwv}?currentSchema=${database.schema:adm_vwv}

management:
  endpoint:
    health:
      probes:
        enabled: true