spring:
  application.name: ris-adm-vwv-backend
  datasource:
    url: jdbc:postgresql://${database.host:localhost}:${database.port:5432}/${database.database:ris_adm_vwv}?currentSchema=${database.schema:adm_vwv}

management:
  endpoint:
    health:
      probes:
        enabled: true

sentry:
  dsn: ${SENTRY_DSN}
  environment: staging
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  tracesSampleRate: 0.1 # 10% of all requests are logged as traces
  sampleRate: 1.0 # 100 % of all errors are logged

frontend:
  auth:
    url: ${oauth2.frontend-url}
    realm: ${oauth2.realm}
    clientId: ${oauth2.client-id}

s3:
  region: ${s3.region}
  endpoint: ${s3.endpoint}
  adm:
    private:
      access-key: ${s3.adm.private.access-key}
      access-key-id: ${s3.adm.private.access-key-id}
      bucket-name: ${s3.adm.private.bucket-name}
