name: "CI Pipeline"

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  
  frontend-checks:
    uses: ./.github/workflows/frontend-jobss.yml
    secrets: inherit


