on:
  workflow_call:

jobs:
  backend-push-reports-to-ris-reports:
    runs-on: ubuntu-latest
    env:
      reports-repo: digitalservicebund/ris-reports
    steps:
      # This step needs to happen before any "add-ris-report" action
      # (otherwise the folder is not git repository and does not support git commands)
      - name: Checkout ris-reports
        uses: actions/checkout@v4
        with:
          repository: ${{ env.reports-repo }}
          ssh-key: ${{ secrets.RIS_REPORTS_DEPLOY_PRIVATE_KEY }}

      ########################################################################
      # Downloading and adding test reports
      # Note: actually pushing the reports is a separate step after all these
      ########################################################################

      ## Backend unit test report
      - name: Download artifact backend unit test report
        uses: actions/download-artifact@v4
        with:
          name: backend-test-report
          path: tmp/backend-test-report/
      - name: Add backend unit test report for push
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/backend-test-report
          destinationDir: test-reports/ris-adm-vwv/backend/tests
          reportIsDirectory: true

      ## Backend license report
      - name: Download artifact backend license report
        uses: actions/download-artifact@v4
        with:
          name: backend-license-report
          path: tmp/backend-license-report/
      - name: Add backend license report for push
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/backend-license-report
          destinationDir: licence-reports/backend/ris-adm-vwv
          reportIsDirectory: true

      ##############################################
      # Finally: pushing the reports to ris-reports
      ##############################################
      - name: Setup git config
        run: |
          git config user.name "${{ github.repository }}"
          # This email identifies the commit as GitHub Actions - see https://github.com/orgs/community/discussions/26560
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name:
          Push reports
          # we use `toJSON(...)` below to escape double quotation marks
        run: |
          git diff-index --cached --quiet HEAD ||
            git commit \
              -m ${{ toJSON(github.event.head_commit.message) }} \
              -m "From commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" &&
            git push origin main &&
            echo "Pushed reports to ${{ github.server_url }}/${{ env.REPORTS_REPOSITORY }}" >> $GITHUB_STEP_SUMMARY
      - name: Send status to Slack
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf # v1.5.0
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
