on:
  workflow_call:

jobs:
  push-e2e-report-to-ris-reports:
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      reports-repo: digitalservicebund/ris-reports
    steps:
      # This step needs to happen before any "add-ris-report" action
      # (otherwise the folder is not git repository and does not support git commands)
      - name: Checkout ris-reports
        uses: actions/checkout@v4
        with:
          repository: ${{ env.reports-repo }}
          ssh-key: ${{ secrets.RIS_REPORTS_DEPLOY_PRIVATE_KEY }}

      ########################################################################
      # Downloading and adding test reports
      # Note: actually pushing the reports is a separate step after all these
      ########################################################################

      - name: Download artifact frontend e2e test report
        uses: actions/download-artifact@v5
        with:
          name: frontend-e2e-test-report-html
          path: tmp/frontend-e2e-test-report-html
      - name: Add frontend e2e test report for push
        uses: digitalservicebund/add-ris-report@c6c8735d23295c36a271c75e7dedc9b6b9a9ef5e
        with:
          filePath: tmp/frontend-e2e-test-report-html
          destinationDir: test-reports/ris-adm-vwv/frontend/e2e-tests
          reportIsDirectory: true

      ##############################################
      # Finally: pushing the reports to ris-reports
      ##############################################
      - name: Setup git config
        run: |
          git config user.name "${{ github.repository }}"
          # This email identifies the commit as GitHub Actions - see https://github.com/orgs/community/discussions/26560
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name:
          Push reports
          # we use `toJSON(...)` below to escape double quotation marks
        run: |
          git diff-index --cached --quiet HEAD ||
            git commit \
              -m ${{ toJSON(github.event.head_commit.message) }} \
              -m "From commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" &&
            git push origin main &&
            echo "Pushed reports to ${{ github.server_url }}/${{ env.REPORTS_REPOSITORY }}" >> $GITHUB_STEP_SUMMARY

      # - name: Send status to Slack
      # we don't handle a failure as a problem (that's why we set "continue-on-error")
      # hence it's certainly not worthy of sending an alarm message
