name: "CI Pipeline"

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    # TODO: restrict later
    # branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  ##############################################
  # jobs dispatched to separate workflow files #
  ##############################################

  frontend-jobs:
    uses: ./.github/workflows/frontend-jobs.yml
    secrets: inherit

  security-jobs:
    if: true = false
    uses: ./.github/workflows/security-jobs.yml
    secrets: inherit # so the backend workflow can access "secrets.SLACK_WEBHOOK_URL" and others
    permissions:
      contents: read
      security-events: write # trivy scan needs this
