name: "CI Pipeline"

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  ########################################
  # Security
  ########################################

  security-jobs:
    uses: ./.github/workflows/security-jobs.yml
    secrets:
      GH_SECRET_SCANNING_TOKEN: ${{ secrets.GH_SECRET_SCANNING_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      security-events: write # trivy scan needs this

  ##############
  # Backend jobs
  ##############

  backend-setup-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup and validate Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a

  backend-checks:
    needs:
      - backend-setup-gradle
    uses: ./.github/workflows/backend-checks.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}

  backend-build-image-and-scan:
    uses: ./.github/workflows/backend-build-image-and-scan.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      security-events: write
    with:
      run-id: ${{ github.run_id }}
      image-ref: ghcr.io/${{ github.repository }}-backend:${{ github.event.pull_request.head.sha || github.sha }}
      container-registry: ghcr.io

  backend-push-image-to-registry:
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'dev-env') }}
    # For PR releases, labels could be used like this:
    # if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'dev-env') || contains(github.event.labeled.labels.*.name, 'dev-env') }}
    needs:
      - security-jobs
      - backend-checks
      - backend-build-image-and-scan
    uses: ./.github/workflows/backend-push-image-to-registry.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      id-token: write # This is used to complete the identity challenge with sigstore/fulcio..
      packages: write
    with:
      run-id: ${{ github.run_id }}
      container-registry: ghcr.io
      image-ref: ghcr.io/${{ github.repository }}-backend:${{ github.event.pull_request.head.sha || github.sha }}

  backend-push-reports-to-ris-reports:
    if: ${{ !cancelled() && github.ref == 'refs/heads/main' }}
    needs:
      - backend-checks
      - frontend-push-reports-to-ris-reports # this is to avoid our reports jobs (backend/frontend) to cause each other to
    uses: ./.github/workflows/backend-push-reports-to-ris-reports.yml
    secrets:
      RIS_REPORTS_DEPLOY_PRIVATE_KEY: ${{ secrets.RIS_REPORTS_DEPLOY_PRIVATE_KEY }}

  ###############
  # Frontend jobs
  ###############

  frontend-checks:
    uses: ./.github/workflows/frontend-checks.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}

  frontend-build-image-and-scan:
    uses: ./.github/workflows/frontend-build-image-and-scan.yml
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      security-events: write
    with:
      run-id: ${{ github.run_id }}
      image-ref: ghcr.io/${{ github.repository }}-frontend:${{ github.event.pull_request.head.sha || github.sha }}

  frontend-push-image-to-registry:
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'dev-env') }}
    # For PR releases, labels could be used like this:
    # if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'dev-env') || contains(github.event.labeled.labels.*.name, 'dev-env') }}
    needs:
      - security-jobs
      - frontend-checks
      - frontend-build-image-and-scan
    uses: ./.github/workflows/frontend-push-image-to-registry.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      contents: read
      id-token: write # This is used to complete the identity challenge with sigstore/fulcio..
      packages: write
    with:
      run-id: ${{ github.run_id }}
      container-registry: ghcr.io
      image-ref: ghcr.io/${{ github.repository }}-frontend:${{ github.event.pull_request.head.sha || github.sha }}

  frontend-push-reports-to-ris-reports:
    if: ${{ !cancelled() && github.ref == 'refs/heads/main' }}
    needs:
      - frontend-checks
    uses: ./.github/workflows/frontend-push-reports-to-ris-reports.yml
    secrets:
      RIS_REPORTS_DEPLOY_PRIVATE_KEY: ${{ secrets.RIS_REPORTS_DEPLOY_PRIVATE_KEY }}

  #######################################
  # e2e tests (frontend & backend)
  #######################################

  e2e-tests: # we may need to split off the report handling in order to avoid pushing two reports at once
    uses: ./.github/workflows/e2e-tests.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  e2e-compile-html-report:
    needs:
      - e2e-tests
    uses: ./.github/workflows/e2e-compile-html-report.yml

  e2e-push-reports-to-ris-reports:
    if: ${{ !cancelled() && github.ref == 'refs/heads/main' }}
    needs:
      - e2e-compile-html-report
      - backend-push-reports-to-ris-reports # don't push at the same time
    uses: ./.github/workflows/e2e-push-reports-to-ris-reports.yml
    secrets:
      RIS_REPORTS_DEPLOY_PRIVATE_KEY: ${{ secrets.RIS_REPORTS_DEPLOY_PRIVATE_KEY }}

  #######################################
  # Automerge if dependabot branch and all tests passing
  #######################################

  dependabot-auto-merge:
    runs-on: ubuntu-latest
    # the ${{ success() }} is required for the "if" not to override the "needs" below
    # (we did run into this problem and saw auto-merges even as "frontend-checks" failed)
    if: ${{ success() && github.actor == 'dependabot[bot]' && !cancelled() && github.ref != 'refs/heads/main' }}
    permissions: write-all
    needs:
      - frontend-checks
      - backend-checks
      - e2e-tests
    steps:
      - name: Dependabot metadata
        continue-on-error: true
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto-merge Dependabot PRs except major version updates
        continue-on-error: true
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #################
  # Deployment jobs
  #################

  deploy-staging:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - security-jobs
      - e2e-tests
      - frontend-checks
      - frontend-build-image-and-scan
      - frontend-push-image-to-registry
      - backend-checks
      - backend-build-image-and-scan
      - backend-push-image-to-registry
    uses: ./.github/workflows/deploy-staging.yml
    permissions:
      id-token: write
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      ARGOCD_PIPELINE_PASSWORD: ${{ secrets.ARGOCD_PIPELINE_PASSWORD }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      METRICS_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
      METRICS_WEBHOOK_TOKEN: ${{ secrets.METRICS_WEBHOOK_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      container-image-version: ${{ github.event.pull_request.head.sha || github.sha }}
