name: "CI Pipeline"

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  ##############################################
  # jobs dispatched to separate workflow files #
  ##############################################

  frontend-jobs:
    uses: ./.github/workflows/frontend-jobs.yml
    secrets: inherit
