on:
  workflow_call:

jobs:
  confirm-repository-secret-scanning-with-push-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt install jq
      - name: Fetch configuration information on repository
        env:
          # the token needs (max) the following permissions:
          # read:enterprise, read:org, read:project, read:user, repo
          GH_TOKEN: ${{ secrets.GH_SECRET_SCANNING_TOKEN }}
        run: gh api --method GET -H "X-GitHub-Api-Version:2022-11-28"  /repos/digitalservicebund/ris-adm-vwv > repo-info.json
      - name: Confirm that secret scanning is active
        run: |
          if [[ $(cat repo-info.json | jq ' .security_and_analysis.secret_scanning.status') == *enabled* ]]; then 
            exit 0; 
          else 
            exit 1
          fi
      - name: Confirm that push protection is active
        run: |
          if [[ $(cat repo-info.json | jq ' .security_and_analysis.secret_scanning_push_protection.status') == *enabled* ]]; then 
            exit 0; 
          else 
            exit 1
          fi
      - name: On failure send status to Slack
        # only on failure and if on "main" branch
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  security-scan-with-trivy:
    # Note: This scan is NOT what is shown in the GitHub Security tab
    #       Please refer to frontend-build-image-and-scan.yml instead
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode # open source security scanner, cf. https://trivy.dev/
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-fs-results.sarif"
          # severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL" #ignored by sarif report
      - name: Print trivy fs results
        run: cat trivy-fs-results.sarif
      - name: Check trivy results
        run: |
          if grep -qE 'HIGH|CRITICAL' trivy-fs-results.sarif; then
            echo "Vulnerabilities found"
            exit 1
          else
            echo "No significant vulnerabilities found"
            exit 0
          fi
      - name: Upload trivy fs scan sarif report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-trivy-fs-results.sarif
          retention-days: 3
          path: trivy-fs-results.sarif
      - name: On failure send status to Slack
        # only on failure and if on "main" branch
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # we should be able to upload the trivy results to the GitHub Security tab as we're a public repositor
      # but right now it's not worth it
      # cf https://digitalservicebund.atlassian.net/browse/RISDEV-5193
