on:
  workflow_call:

jobs:
  security-scan-with-trivy:
    # Note: This scan is NOT what is shown in the GitHub Security tab
    #       Please refer to frontend-build-image-and-scan.yml instead
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode # open source security scanner, cf. https://trivy.dev/
        uses: aquasecurity/trivy-action@cf990b19d84bbbe1eb8833659989a7c1029132e3
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-results.sarif"
          # severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL" #ignored by sarif report
      - name: Check trivy results
        run: |
          if grep -qE 'HIGH|CRITICAL' trivy-results.sarif; then
            echo "Vulnerabilities found"
            exit 1
          else
            echo "No significant vulnerabilities found"
            exit 0
          fi
      - name: On failure send status to Slack
        # only on failure and if on "main" branch
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # we should be able to upload the trivy results to the GitHub Security tab as we're a public repositor
      # but right now it's not worth it
      # cf https://digitalservicebund.atlassian.net/browse/RISDEV-5193

  secrets-scan-with-talisman: # scan for secrets that were published by mistake (we have a pre-commit and pre-push hook, but who knows)
    runs-on: ubuntu-latest
    # Running on main only (branches pose problems, cf. https://digitalservicebund.slack.com/archives/C046VD44ZEH/p1706516240974409)
    if: ${{ github.ref == 'refs/heads/main' }}
    # Mitigation by activating Secret Scanning and Push Protection in GitHub Repo Settings
    # cf. https://digitalservicebund.slack.com/archives/C046VD44ZEH/p1706525248390559
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect secrets in incoming commits with Talisman
        uses: digitalservicebund/talisman-secrets-scan-action@9a4cb85589e29a62b4546eb566119753a5680aeb
      - name: On failure send status to Slack
        # only on failure and if on "main" branch
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
